contacts/urls.py
from django.conf.urls import url
from . import views


app_name = 'contacts'

urlpatterns = [
    url(r'^add/$', views.add, name='add'),
    url(r'^list/$', views.list, name='list'),
    url(r'^success/$', views.success, name='success'),
    url(r'^$', views.index , name='index'),

]

employee_mgt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('contacts.urls')),
    url(r'^admin/', admin.site.urls),
]

contacts/models.py
from django.db import models
from .validators import validate_name

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=20, verbose_name='Name', validators=[validate_name])
    email = models.EmailField(max_length=255, verbose_name='Email')

contacts/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    error_css_class = 'error'

    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'name' : forms.TextInput(attrs={'placeholder':'Enter Full name'}),
            'email': forms.EmailInput(attrs={'placeholder':'Enter Email'})
        }

contacts/views.py
from django.shortcuts import render, reverse
from django.http import request
from django.http.response import HttpResponse, HttpResponseRedirect
from .forms import EmployeeForm
from .models import Employee

# Create your views here.

def index(request):
    '''
    Displays the home page
    :param request: The Http request object
    :return: Returns a django.http.response.HttpResponse object
    '''
    return render(request, 'contacts/index.html')

def list(request):
    '''
    Handles logic to display a list of all records in the database
    :param request: The Http request object
    :return: Returns a django.http.response.HttpResponse object
    '''

    records = Employee.objects.all()
    return render(request, 'contacts/list.html', {'records': records})


def add(request):
    '''
    Handles logic to display and add a contact
    :param request: The Http request object
    :return: Returns a django.http.response.HttpResponse object
    '''
    if request.method == 'POST':

        form = EmployeeForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('contacts:success'))
    else:
        form = EmployeeForm()

    return render(request, 'contacts/form.html', {'form':form})


def success(request):
    '''
    Display success page after contact is successfully added
    :param request:  The Http Request object
    :return: Returns a django.http.response.HttpResponse Object

    '''
    return render(request, 'contacts/success.html')

contacts/templates/contacts/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'contacts/css/style.css' %}" rel="stylesheet"/>
</head>
<body>
    <div id="container">
        <div id="header"><a href="{% url 'contacts:index' %}"><img src="{% static 'contacts/images/contacts.png' %}" width="50px" height='50px' /><span>Employee Contacts App</span></a></div>
        <div id="content">{% block content %}{% endblock content %}</div>
        <div id="footer">&copy; 2016 Employee Contacts App</div>
    </div>

</body>
</html>

contacts/templates/contacts/form.html
{% extends "contacts/base.html" %}

{% block title %}Add Contact{% endblock title %}

{% block content %}
    <div><h3>Add Contact</h3></div>

    <form action="{% url 'contacts:add' %}" method="POST">
        {% csrf_token %}

        {{ form.name }}<br/>
        {% if form.errors.name %}
            {% for error in form.errors.name %}
                {{error}}
            {% endfor %}
        {% endif %}
        <br/><br/>
        {{ form.email }}<br/>
        {% if form.errors.email %}
            {% for error in form.errors.email %}
                {{ error }}
            {% endfor %}
        {% endif %}
        <br/></br/>
        <input type="submit" value="Add Contact" />
    </form>
{% endblock content %}

contacts/templates/contacts/index.html
{% extends "contacts/base.html" %}
{% block title %}Home- Employee Contacts App{% endblock title %}
{% block content %}
    <p><a href="{% url 'contacts:add' %}">Add Contact</a></p>
    <p><a href="{% url 'contacts:list' %}">List All Contacts</a></p>
{% endblock content %}

contacts/templates/contacts/list.html
{% extends 'contacts/base.html' %}

{% block title %} List of Records{% endblock title %}

{% block content %}
    <h2>Contacts List</h2>
    {% if not records %}
        <h4> No Contact found </h4>
        <a href="{% url 'contacts:add' %}">Add new contact</a>
        {% else %}
            <table border="1px solid" align="center">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                </tr>

                {% for record in records %}
                    <tr>
                        <td>{{record.name}}</td>
                        <td>{{record.email}}</td>
                    </tr>
                {% endfor %}
            </table>
    {% endif %}
{% endblock content %}

contacts/templates/contacts/success.html
{% extends "contacts/base.html" %}

{% block title %}Success{% endblock title %}

{% block content %}
    <h2>Contact Successfully Added</h2>
{% endblock content %}